homemingle/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

homemingle/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('terms_of_use/', views.terms_of_use, name='terms_of_use'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

homemingle/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

homemingle/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

homemingle/puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homemingle/core/models.py
from django.db import models

# Create your models here.

homemingle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

homemingle/core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item

from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def about(request):
    return render(request, 'core/about.html')

def contact(request):
    return render(request, 'core/contact.html')

def privacy_policy(request):
    return render(request, 'core/privacy_policy.html')

def terms_of_use(request):
    return render(request, 'core/terms_of_use.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

homemingle/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">About</h1>

    <div class="space-y-6">
        Welcome to our online home accessories trading platform! We are a vibrant community dedicated to connecting home-loving individuals who are passionate about finding unique and stylish pieces for their living spaces. Our platform provides a seamless and enjoyable experience, allowing you to search for the perfect items to enhance your home and sell your own treasures to others.

        At our platform, you'll discover an extensive collection of home accessories sourced from around the world. From exquisite artwork and decorative pieces to functional and practical items, we offer a wide range of options to suit every style and taste. Whether you're searching for that one-of-a-kind vintage lamp, a cozy throw blanket, or elegant kitchenware, our platform is your go-to destination.

        We understand that your home is a reflection of your personal style, and we strive to provide a curated selection of items that inspire and elevate your living spaces. Our platform features a user-friendly search function that allows you to effortlessly browse through categories, filter results, and find exactly what you're looking for. You can explore various themes, trends, and aesthetics to discover unique treasures that will add a touch of charm and personality to your home.

        In addition to being a shopping paradise, our platform also empowers you to become a seller and share your own home accessories with our community. If you have items that no longer fit your decor or are looking to refresh your space, you can easily list them for sale. Our platform provides a straightforward selling process, allowing you to showcase your items through detailed descriptions and high-quality images. You'll have the opportunity to connect with like-minded individuals who appreciate your style and offer your treasures a new home.

        As a dedicated team of home enthusiasts, we are committed to creating a secure and enjoyable trading experience for all our users. We prioritize safety and trust, implementing robust measures to protect your personal information and facilitate transparent transactions. Our platform also fosters a sense of community, where you can engage in discussions, seek advice, and share your love for all things home-related with fellow enthusiasts.

        Join our online home accessories trading platform today and embark on a journey to transform your living spaces into havens of beauty and comfort. Start exploring, connecting, and trading to curate a home that truly reflects your unique style and personality. Together, let's make every space a place to cherish and enjoy.
    </div>
{% endblock %}

homemingle/core/templates/core/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <script src="https://cdn.tailwindcss.com"></script>
        
        <title>{% block title %}{% endblock %} | HomeMingle</title>
    </head>

    <body>
        <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">HomeMingle</a>

            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="px-6 py-6 flex justify-between bg-gray-800">
            <div class="w-4/5 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-lg text-gray-500">Welcome to HomeMingle, your premier online home accessories trading platform. 
                    Find and sell unique items for your living spaces with ease. 
                    Discover curated collections of stylish and functional pieces sourced from around the world. 
                    Join our community, browse categories, and connect with like-minded individuals. 
                    Transform your home decor with HomeMingle today!</p>
            </div>

            <div class="w-1/5">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="{% url 'core:about' %}" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="{% url 'core:privacy_policy' %}" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                    <li><a href="{% url 'core:terms_of_use' %}" class="text-lg text-teal-500 hover:text-teal-700">Terms of Use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

homemingle/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">The Contact Page</h1>
{% endblock %}

homemingle/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

homemingle/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

homemingle/core/templates/core/privacy_policy.html
{% extends 'core/base.html' %}

{% block title %}Privacy Policy{% endblock %}

{% block content %}
    <h1 class="mb-6 mx-auto text-3xl">Privacy Policy</h1>
    <div class="p-6 flex bg-gray-100 rounded-xl">
        At HomeMingle, we value your privacy and are committed to protecting your personal information. This Privacy Policy outlines how we collect, use, and safeguard the data you provide to us through our platform. By using HomeMingle, you agree to the terms and practices described below.<br>

        Information Collection:
        We collect certain personal information when you register an account, browse items, make purchases, or communicate with other users. This may include your name, email address, contact details, and other relevant information.<br>
        Use of Information:
        We use the collected information to provide you with a personalized and seamless trading experience on HomeMingle. This includes facilitating transactions, improving our services, communicating with you about your account and transactions, and sending relevant updates and promotional offers.<br>
        Data Security:
        We take appropriate measures to ensure the security of your personal information. We utilize industry-standard encryption and secure server infrastructure to protect your data from unauthorized access, disclosure, alteration, or destruction.<br>
        Sharing of Information:
        We may share certain information with trusted third-party service providers to assist us in delivering our services effectively. These service providers are bound by confidentiality agreements and are only authorized to use your information to perform specific tasks on our behalf.<br>
        Cookies and Tracking Technologies:
        HomeMingle may use cookies and similar tracking technologies to enhance your browsing experience and gather information about usage patterns. These technologies help us analyze trends, track user movements, and provide relevant content and advertisements.<br>
        Third-Party Links:
        Our platform may contain links to third-party websites or services. Please note that this Privacy Policy does not apply to any external sites or services. We encourage you to review the privacy policies of those third parties before providing any personal information.<br>
        Changes to the Privacy Policy:
        We reserve the right to update or modify this Privacy Policy at any time. Any changes made will be reflected on this page, and we encourage you to review it periodically. Your continued use of HomeMingle signifies your acceptance of any modifications.<br>
        If you have any questions or concerns about our Privacy Policy or the security of your personal information, please contact us at privacy@homemingle.com. Your privacy is of utmost importance to us, and we are dedicated to addressing any inquiries promptly and responsibly.<br>

        Last Updated: May 25, 2023
    </div>
{% endblock %}

homemingle/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

homemingle/core/templates/core/terms_of_use.html
{% extends 'core/base.html' %}

{% block title %}Terms of Use{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">Terms of Use</h1>
    <div class="p-6 flex bg-gray-100 rounded-xl">
        Please read these Terms of Use ("Terms") carefully before using HomeMingle ("the Platform"). 
        By accessing or using the Platform, you agree to be bound by these Terms.<br><br>

        Account Registration:<br>
        To access certain features of the Platform, you may be required to create an account. <br>
        You are responsible for providing accurate and up-to-date information during the registration process. <br>
        You must be at least 18 years old to create an account on HomeMingle.<br><br>

        Platform Usage:<br>
        a. You agree to use the Platform solely for lawful purposes and in accordance with these Terms. <br>
        You will not engage in any activity that may disrupt or interfere with the operation of the Platform or the experiences of other users.<br>
        b. You are solely responsible for any content you post, including product listings, comments, and messages. <br>
        You agree not to post any content that is illegal, offensive, defamatory, or violates the rights of others.<br><br>
        
        Transactions:<br>
        a. HomeMingle provides a platform for users to buy and sell home accessories. <br>
        We are not involved in the actual transactions between users and do not assume any responsibility for the quality, safety, or legality of the items listed.<br>
        b. Buyers and sellers are responsible for communicating, negotiating, and fulfilling transactions. Any issues or disputes should be resolved directly between the parties involved.<br><br>
        
        Intellectual Property:<br>
        a. The Platform and its content, including logos, text, images, and trademarks, are protected by intellectual property laws. You may not use, modify, or distribute any content from the Platform without prior written consent.<br>
        b. By posting content on the Platform, you grant HomeMingle a non-exclusive, royalty-free, worldwide license to use, display, and distribute the content for promotional and marketing purposes.<br><br>
        
        Limitation of Liability:<br>
        a. HomeMingle is provided on an "as is" and "as available" basis. We make no warranties or representations regarding the accuracy, completeness, or reliability of the Platform or its content.<br>
        b. In no event shall HomeMingle or its affiliates be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the Platform or any transactions conducted through it.<br><br>
        
        Termination:<br>
        HomeMingle reserves the right to suspend or terminate your account at any time and for any reason, without prior notice or liability. You may also terminate your account by contacting us.<br><br>
        
        Governing Law:<br>
        These Terms shall be governed by and construed in accordance with the laws of [Jurisdiction]. Any disputes arising from these Terms or your use of the Platform shall be subject to the exclusive jurisdiction of the courts in [Jurisdiction].<br>
        By using HomeMingle, you agree to comply with these Terms. If you have any questions or concerns, please contact us at support@homemingle.com.<br><br>

        Last Updated: May 25, 2023<br>
    </div>
{% endblock %}